language: java
script:
  - mvn clean verify
  - docker build -t "$id-dockerhub"/backend sample-application-http-api-server/.
  - docker build -t "$id-dockerhub"/database sample-application-db-changelog-job/.
  - docker login -u "$id-dockerhub" -p "$token-dockerhub"
  - docker push "$id-dockerhub"/backend
  - docker push "$id-dockerhub"/database